version: '3.3'

services:
   db:
     image: sqlt:1.0
     volumes:
     - db_data:/var/lib/mysql
     restart: always
     environment:
        MYSQL_ROOT_PASSWORD: root123
        MYSQL_DB_NAME: wordpress
        MYSQL_DB_USER: wpuser
        MYSQL_DB_PASSWORD: cninnovation

   wordpress:
     depends_on:
       - db
     image: wpt:1.0
     ports:
       - "8080:80"
     restart: always
     environment:
        WORDPRESS_DB_NAME: wordpress
        WORDPRESS_DB_USER: wpuser
        WORDPRESS_DB_PASSWORD: cninnovation
        WORDPRESS_DB_HOST: db:3306
volumes:
    db_data: {}