apiVersion: v1
kind: Service # specifies the resource as service
metadata:
  name: wordpress # specified name of the service
  labels: # labels of the service
    app: wordpress 
spec:
  ports:
    - port: 80 # ports that are exposed by the service
  selector: # select pods deployed in the later specified deployment
    app: wordpress
    tier: frontend
  type: LoadBalancer # specify external load balancer
---
apiVersion: v1
kind: PersistentVolumeClaim # specifies the resource as persistent volume claim
metadata:
  name: wp-pv-claim # specified name of the persistent volume claim
  labels: # labels of the persistent volume claim
    app: wordpress 
spec:
  accessModes:
    - ReadWriteOnce # can be mounted as read-write by a single node
  resources:
    requests:
      storage: 20Gi # request 20gb storage
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: wordpress # specified name of the deployment
  labels: # labels of the deployment
    app: wordpress
spec:
  selector:
    matchLabels: # link pods labelled like this to the deployment
      app: wordpress
      tier: frontend
  strategy:
    type: Recreate
  template: # template for created pods
    metadata:
      labels: # labels of the pods created by this deployment
        app: wordpress
        tier: frontend
    spec:
      containers:
      - image: wordpress:4.8-apache # specify image
        name: wordpress # specify container name
        env:
        - name: WORDPRESS_DB_HOST
          value: wordpress-mysql # service that is associated to the wordpress-mysql deployment
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass # take value from the created secret
              key: password # select the password
        ports:
        - containerPort: 80 # exposed port
          name: wordpress # ???
        volumeMounts:
        - name: wordpress-persistent-storage # name of the volume
          mountPath: /var/www/html # specify the path of to be persisted volume
      volumes:
      - name: wordpress-persistent-storage # link to the former created volumeMount
        persistentVolumeClaim:
          claimName: wp-pv-claim # link to the former created PersistantVolumeClaim